### ISSUE TITLE
How to turn off Doppler factor

### ISSUE THREAD

**Issue by wwtinwhu** [utiasASRL/steam_icp#2]
Hello, @cheneyuwu! Nice Work! How to disable the Doppler factor and test the STEAM-ICP?

**Comment by cheneyuwu** [comment]
Hello,

You can disable it by setting `use_rv` to false in the config file:
https://github.com/utiasASRL/steam_icp/blob/b13bf47b44ddb8071f163d775edbf803c7eb82c8/steam_icp/config/default_config.yaml#L37
