### ISSUE TITLE
Where should the dataset place ?

### ISSUE THREAD

**Issue by kahowang** [utiasASRL/steam_icp#4]
Hello, thanks for your nice job, can you tell me when i run the docker which was provided by you, i dont know where to place the Aeva dataset, and how to play this bag? 

Looking for your reply ~

**Comment by cheneyuwu** [comment]
Hi Kaho,

You may update or create you own config file like [this one](https://github.com/utiasASRL/steam_icp/blob/picking_up_speed/steam_icp/config/default_config.yaml) and pass it into the experiment script, e.g. 
```bash
ros2 run steam_icp steam_icp --ros-args --params-file ${WORKING_DIR}/steam_icp/config/default_config.yaml
```
It defines the `log`, `output`,  `debug`, `dataset (root_path)` directories that you can set to your desired ones.  

Usually the dataset is downloaded to your machine and with its root directory mounted into the container (via `-v`)

Yuchen

**Comment by kahowang** [comment]
Hi cheneyu,
Thank you very much for your previous reply, currently I am running steam-icp, but there are some problems when I am running  `ros2 run steam_icp steam_icp --ros-args --params-file ${WORKING_DIR}/steam_icp/config/aeva.yaml .`The terminal has a lot of outputs, but I can't see anything in Rviz (use command line is `ros2 run rviz2 rviz2 -d ${WORKING_DIR}/steam_icp/rviz/steam_icp.rviz)` , meanwhile use `ros2 topic echo /steam_icp_raw`
cannot echo some msg.

![docker](https://github.com/utiasASRL/steam_icp/assets/35909921/0b2257df-0323-412f-bc7b-39a36468e8df)
![image](https://github.com/utiasASRL/steam_icp/assets/35909921/5041f752-833f-4684-aec2-81a9ed16f3a2)
![image](https://github.com/utiasASRL/steam_icp/assets/35909921/1b99ca9d-efea-4bd5-a422-278026837e7d)

Looking forward for  your reply ~

Kaho

**Comment by cheneyuwu** [comment]
Hi, could you turn on the corresponding visualization flags in your config file:
![image](https://github.com/utiasASRL/steam_icp/assets/28690905/ad48ef8e-c3c1-4514-adaf-f3684de591e5)

**Comment by chengwei0427** [comment]
Hi, @kahowang @
I have a question about build this project. The error is as follows,
Can you tell me how you solved the problem? Thanks.
![2024-03-05 15-12-57屏幕截图](https://github.com/utiasASRL/steam_icp/assets/20199999/eb8c0a89-bdd4-46ec-9d9c-1e8230779fe3)

**Comment by kahowang** [comment]
> Hi, @kahowang @ I have a question about build this project. The error is as follows, Can you tell me how you solved the problem? Thanks. ![2024-03-05 15-12-57屏幕截图](https://private-user-images.githubusercontent.com/20199999/310017862-eb8c0a89-bdd4-46ec-9d9c-1e8230779fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTc3MjAsIm5iZiI6MTcwOTY5NzQyMCwicGF0aCI6Ii8yMDE5OTk5OS8zMTAwMTc4NjItZWI4YzBhODktYmRkNC00NmVjLTlkOWMtMWU4MjMwNzc5ZmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAzNTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkN2ZlMzExMWE0Y2VjNzVjMjkzYTBlNmE5OTE0MDc3OTI0YmNmMWU0MjJhNDY5NTg2ZTFkOWFjNzM0ZmM2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qN48OqpXvcfNWl5nN2yslmh623O7HuX9kjy1CjcuQfc)

你好，成伟
 这个工程我很久之前运行，现在有点忘记了。我记得我执行这一步时，也遇到这个问题，后面我改了一下dockerFile，我分享给您，希望对你有帮助~

kaho

[Dockerfile-New-With-Sudo.zip](https://github.com/utiasASRL/steam_icp/files/14504441/Dockerfile-New-With-Sudo.zip)

**Comment by chengwei0427** [comment]
Hi, @kahowang , Thank you very much. I will test it and give you a feedback.

**Comment by kahowang** [comment]
> Hi, @kahowang , Thank you very much. I will test it and give you a feedback.

不用客气，期待你的回复~
