### ISSUE TITLE
How to download boreas(aeva) dataset?

### ISSUE THREAD

**Issue by HelloDuoLA** [utiasASRL/steam_icp#7]
I saw the boreas_aeva_config.yaml file in the repository, how do I download this dataset?

**Comment by keenan-burnett** [comment]
We have a link to this in the readme for this repo.
https://drive.google.com/file/d/1JpQNnXejow3qy1qp5tVzak9qnuFmjYHW/view?usp=share_link

**Comment by HelloDuoLA** [comment]
Are both steam_icp/steam_icp/config/aeva_config.yaml and steam_icp/steam_icp/config/boreas_aeva_config.yaml  configurations for this dataset?

**Comment by keenan-burnett** [comment]
use `boreas_aeva_config.yaml`

**Comment by HelloDuoLA** [comment]
Well, thank you for your answer.
